"""MCP server exposing SQLite-backed research storage tools over stdio."""

import json
import sqlite3
from pathlib import Path

from mcp.server.fastmcp import FastMCP

DB_PATH = Path(__file__).parent / "research.db"

mcp = FastMCP("research-assistant")


def _get_connection() -> sqlite3.Connection:
    """Open a SQLite connection and ensure the research table exists."""
    conn = sqlite3.connect(DB_PATH)
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS research (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            summary TEXT NOT NULL,
            sources TEXT NOT NULL,
            timestamp TEXT NOT NULL
        )
        """
    )
    conn.commit()
    return conn


@mcp.tool()
def save_research(
    title: str, summary: str, sources: list[str], timestamp: str
) -> str:
    """Save a research entry into the SQLite database.

    Args:
        title: Short title or topic of the research (typically the user query).
        summary: Structured summary text generated by the LLM.
        sources: List of source URLs; stored as a JSON array string.
        timestamp: ISO 8601 formatted timestamp of when the research was saved.

    Returns:
        Confirmation string containing the saved title.
    """
    conn = _get_connection()
    try:
        conn.execute(
            "INSERT INTO research (title, summary, sources, timestamp) VALUES (?, ?, ?, ?)",
            (title, summary, json.dumps(sources), timestamp),
        )
        conn.commit()
        return f"Saved research: {title}"
    finally:
        conn.close()


@mcp.tool()
def list_research() -> str:
    """List every research entry currently stored in the database.

    Returns:
        Formatted string with id, title, and timestamp for each entry,
        or "No research entries found." when the table is empty.
    """
    conn = _get_connection()
    try:
        rows = conn.execute(
            "SELECT id, title, timestamp FROM research ORDER BY id DESC"
        ).fetchall()
    finally:
        conn.close()

    if not rows:
        return "No research entries found."

    lines = [f"[{row[0]}] {row[1]}  —  {row[2]}" for row in rows]
    return "\n".join(lines)


@mcp.tool()
def search_research(keyword: str) -> str:
    """Search research entries whose title or summary contains the keyword.

    Args:
        keyword: Case-insensitive keyword to search for.

    Returns:
        Formatted string of matching entries, or a no-match message.
    """
    pattern = f"%{keyword}%"
    conn = _get_connection()
    try:
        rows = conn.execute(
            """
            SELECT id, title, summary, timestamp
            FROM research
            WHERE title LIKE ? COLLATE NOCASE
               OR summary LIKE ? COLLATE NOCASE
            ORDER BY id DESC
            """,
            (pattern, pattern),
        ).fetchall()
    finally:
        conn.close()

    if not rows:
        return f"No matches found for: {keyword}"

    blocks = []
    for row_id, title, summary, timestamp in rows:
        blocks.append(
            f"[{row_id}] {title}  —  {timestamp}\n{summary}"
        )
    return "\n\n".join(blocks)


if __name__ == "__main__":
    mcp.run(transport="stdio")
